---
name: Default

on:
  push:
    tags: [ v* ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run echo
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Run echo
        run: echo "build"

  deploy:
    runs-on: ubuntu-latest
    needs: [ test, build ]
    steps:
      - name: Run echo
        run: echo "deploy"

