---
name: Default

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ""
          POSTGRES_HOST_AUTH_METHOD: trust
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Set up golangci-lint
        run: |
          wget -q https://github.com/golangci/golangci-lint/releases/download/v1.33.0/golangci-lint-1.33.0-linux-amd64.tar.gz
          tar xvzf golangci-lint-1.33.0-linux-amd64.tar.gz
          sudo mv golangci-lint-1.33.0-linux-amd64/golangci-lint /usr/local/bin
      - name: Connect to postgres
        run: ping -c 3 postgres
      - name: Run echo
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

#  build:
#    runs-on: ubuntu-latest
#    needs: test
#    strategy:
#      matrix:
#        env: [ staging, production ]
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#      - name: Run echo
#        run: go build -o hello main.go
