---
name: Default

on:
  push:
    tags: [ v* ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run echo
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  build:
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        env: [ staging, production ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run echo
        run: go build -o hello main.go
