---
name: Default

on:
  push:
    tags: [ v* ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run echo
        run: echo "test ${{ github.head_ref }},  ${{ github.action.base_ref }},  ${{ github.action.head_ref }}, ${{ github.action }}"

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Run echo
        run: echo "build"

  deploy:
    runs-on: ubuntu-latest
    needs: [ test, build ]
    steps:
      - name: Run echo
        run: echo "deploy"

