---
name: Release

on:
  push:
    tags: [ v* ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run echo
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  build:
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        env: [ staging, production ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run echo
        run: go build -o hello main.go

  deploy:
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - name: Run echo
        run: echo "deploy"


  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
