---
name: Release

on:
  push:
    branches: [ release ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run echo
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  deploy:
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - name: Run echo
        run: echo "deploy"

